all:series60

distclean: clean
	$(MAKE) -f Makefile.series60 distclean

clean:
	$(MAKE) -f Makefile.series60 clean

series60:
	$(MAKE) -f Makefile.series60 clean
	$(MAKE) -f Makefile.series60

UIQ:
	$(MAKE) -f Makefile.UIQ clean
	$(MAKE) -f Makefile.UIQ
